### PR TITLE
fix: moved GetProviderHttpClient to separated package

### PR DESCRIPTION
**Pull request by voikin**
I solved the problem of cyclic dependence by putting the functionality in a separate package as an interface, and left the implementation in object/provider

I have taken out only one function from this functionality, but I plan to complement the interface

### CODE REVIEW

**Comment by dplynskiy** [comment]
Please explain which circular dependency problem you are referring to?

**Comment by voikin** [comment]
> Please explain which circular dependency problem you are referring to?

In `OpenIDProvider.TestConnection()` we need to use `GetProviderHttpClient()` from the `object` package

**Comment by dplynskiy** [comment]
> > Please explain which circular dependency problem you are referring to?
> 
> @dplynskiy, In `OpenIDProvider.TestConnection()` we need to use `GetProviderHttpClient()` from the `object` package

I really appreciate your work but empty struct and interface looks strange for solving cyclic dependency problem, mb we should refactor code to divide code on different package/layers, e.g HttpClientFabric with repo dependency with GetCert method, or we can setHttpClient in controller TestConnection before we calling idProvider.TestConnection (as it realized at updateOpenIDWithUrls func in application.go) so logic with cert processing will not be called from the idp package. 

What do you think about it?

**Comment by voikin** [comment]
> > > Please explain which circular dependency problem you are referring to?
> > 
> > 
> > @dplynskiy, In `OpenIDProvider.TestConnection()` we need to use `GetProviderHttpClient()` from the `object` package
> 
> I really appreciate your work but empty struct and interface looks strange for solving cyclic dependency problem, mb we should refactor code to divide code on different package/layers, e.g HttpClientFabric with repo dependency with GetCert method, or we can setHttpClient in controller TestConnection before we calling idProvider.TestConnection (as it realized at updateOpenIDWithUrls func in application.go) so logic with cert processing will not be called from the idp package.
> 
> What do you think about it?

yes, it's a good idea

the reason why I did this is because it seemed to me that this solution was the easiest and fastest

but apparently this task does not require speed, so I will do it right

**Pull request closed without merging**
